inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - vendor/**/*
